Algoritmo "Notas"
Var

nota1,nota2,nota3,nota4,media: real


Inicio
   escreva("Informe a nota da prova 01: ")
     leia (nota1)
   escreva("Informe a nota da prova 02: ")
     leia (nota2)
   escreva("Informe a nota da prova 03: ")
     leia (nota3)
   escreva("Informe a nota da prova 04: ")
     leia (nota4)

   media:= (nota1+nota2+nota3+nota4)/4
     
   escreva("A média ponderada das avaliações foi: ",media)

Fimalgoritmo