Algoritmo "Calculadora de Idade"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
Var
idade,nascimento: real

//aniversario:logico


Inicio
      Escreva("Em que ano você nasceu? ")
      Leia (nascimento)
      //Escreval("Você já comemorou seu aniversário neste ano?")
      //Leia

      idade:= 2022 - nascimento

      escreval("Neste ano, você tem ", idade, " anos de idade")

Fimalgoritmo